"""
Constants for the 2025 Reefscape robot.

All CAN IDs, PID gains, swerve module configurations, and physical constants.
Translated from TunerConstants.java (generated by CTRE Tuner X).
"""

import math

from phoenix6.configs import (
    CANcoderConfiguration,
    CurrentLimitsConfigs,
    Slot0Configs,
    TalonFXConfiguration,
)
from phoenix6.signals import (
    StaticFeedforwardSignValue,
)
from phoenix6.swerve import (
    SwerveDrivetrainConstants,
    SwerveModuleConstants,
)
from phoenix6.swerve.swerve_module_constants import (
    ClosedLoopOutputType,
    DriveMotorArrangement,
    SteerFeedbackType,
    SteerMotorArrangement,
)

# ---------------------------------------------------------------------------
# CAN IDs
# ---------------------------------------------------------------------------

# Pigeon2 IMU
PIGEON2_ID = 0

# Power Distribution Hub
PDH_ID = 1

# Swerve module CAN IDs (steer motors)
FL_STEER_ID = 6
FR_STEER_ID = 5
BL_STEER_ID = 7
BR_STEER_ID = 2

# Swerve module CAN IDs (drive motors)
FL_DRIVE_ID = 18
FR_DRIVE_ID = 17
BL_DRIVE_ID = 19
BR_DRIVE_ID = 20

# Swerve module CAN IDs (CANcoders)
FL_ENCODER_ID = 14
FR_ENCODER_ID = 13
BL_ENCODER_ID = 15
BR_ENCODER_ID = 16

# Climber
CLIMBER_ID = 25

# Elevator
ELEVATOR_LEFT_ID = 31  # leader
ELEVATOR_RIGHT_ID = 30  # follower

# Coral launcher
LAUNCHER_LEFT_ID = 47
LAUNCHER_RIGHT_ID = 48

# ---------------------------------------------------------------------------
# Elevator constants
# ---------------------------------------------------------------------------

ELEVATOR_LEVELS = [0.0, 3.0, 9.5, 22.0, 42.0]  # rotations for each level
ELEVATOR_PID = Slot0Configs()
ELEVATOR_PID.k_p = 0.1
ELEVATOR_PID.k_i = 0.0
ELEVATOR_PID.k_d = 0.01
ELEVATOR_PID.k_v = 0.0
ELEVATOR_PID.k_s = 0.05
ELEVATOR_PID.k_a = 0.001

# ---------------------------------------------------------------------------
# Climber constants
# ---------------------------------------------------------------------------

CLIMBER_SPEED = 0.05  # duty cycle output

# ---------------------------------------------------------------------------
# Coral launcher constants
# ---------------------------------------------------------------------------

LAUNCHER_SPEED = 1.5
AUTO_LAUNCHER_SPEED = LAUNCHER_SPEED / 2  # half speed for level 1 scoring

# ---------------------------------------------------------------------------
# Swerve drive constants
# ---------------------------------------------------------------------------

# PID gains for steer motors
STEER_GAINS = Slot0Configs()
STEER_GAINS.k_p = 100
STEER_GAINS.k_i = 0
STEER_GAINS.k_d = 0.5
STEER_GAINS.k_s = 0.1
STEER_GAINS.k_v = 2.66
STEER_GAINS.k_a = 0
STEER_GAINS.static_feedforward_sign = StaticFeedforwardSignValue.USE_CLOSED_LOOP_SIGN

# PID gains for drive motors
DRIVE_GAINS = Slot0Configs()
DRIVE_GAINS.k_p = 0.1
DRIVE_GAINS.k_i = 0
DRIVE_GAINS.k_d = 0
DRIVE_GAINS.k_s = 0
DRIVE_GAINS.k_v = 0.124

# Closed-loop output types
STEER_CLOSED_LOOP_OUTPUT = ClosedLoopOutputType.VOLTAGE
DRIVE_CLOSED_LOOP_OUTPUT = ClosedLoopOutputType.VOLTAGE

# Motor and encoder types
DRIVE_MOTOR_TYPE = DriveMotorArrangement.TALON_FX_INTEGRATED
STEER_MOTOR_TYPE = SteerMotorArrangement.TALON_FX_INTEGRATED
STEER_FEEDBACK_TYPE = SteerFeedbackType.FUSED_CANCODER

# Slip current (stator current at which wheels start to slip)
SLIP_CURRENT = 120.0  # amps

# Theoretical free speed at 12V
SPEED_AT_12V = 5.96  # meters per second

# Coupling ratio (azimuth rotation -> drive motor turns)
COUPLE_RATIO = 3.125

# Gear ratios
DRIVE_GEAR_RATIO = 5.357142857142857
STEER_GEAR_RATIO = 21.428571428571427

# Wheel radius
WHEEL_RADIUS = 0.0508  # 2 inches in meters

# Side inversion
INVERT_LEFT_SIDE = False
INVERT_RIGHT_SIDE = True

# Steer current limit config
STEER_INITIAL_CONFIGS = TalonFXConfiguration()
_steer_current = CurrentLimitsConfigs()
_steer_current.stator_current_limit = 60
_steer_current.stator_current_limit_enable = True
STEER_INITIAL_CONFIGS.current_limits = _steer_current

DRIVE_INITIAL_CONFIGS = TalonFXConfiguration()
ENCODER_INITIAL_CONFIGS = CANcoderConfiguration()

# Simulation parameters
STEER_INERTIA = 0.01  # kg*m^2
DRIVE_INERTIA = 0.01  # kg*m^2
STEER_FRICTION_VOLTAGE = 0.2  # volts
DRIVE_FRICTION_VOLTAGE = 0.2  # volts

# CAN bus name (empty string = default rio bus)
CAN_BUS_NAME = ""

# Module positions (13 inches from center = 0.3302 m)
MODULE_OFFSET_M = 0.3302  # 13 inches in meters

# ---------------------------------------------------------------------------
# Per-module configuration
# ---------------------------------------------------------------------------

# Front Left
FL_ENCODER_OFFSET = 0.420166015625  # rotations
FL_STEER_INVERTED = True
FL_ENCODER_INVERTED = False
FL_X_POS = MODULE_OFFSET_M
FL_Y_POS = MODULE_OFFSET_M

# Front Right
FR_ENCODER_OFFSET = -0.38525390625  # rotations
FR_STEER_INVERTED = True
FR_ENCODER_INVERTED = False
FR_X_POS = MODULE_OFFSET_M
FR_Y_POS = -MODULE_OFFSET_M

# Back Left
BL_ENCODER_OFFSET = 0.050537109375  # rotations
BL_STEER_INVERTED = True
BL_ENCODER_INVERTED = False
BL_X_POS = -MODULE_OFFSET_M
BL_Y_POS = MODULE_OFFSET_M

# Back Right
BR_ENCODER_OFFSET = -0.197265625  # rotations
BR_STEER_INVERTED = True
BR_ENCODER_INVERTED = False
BR_X_POS = -MODULE_OFFSET_M
BR_Y_POS = -MODULE_OFFSET_M


# ---------------------------------------------------------------------------
# Drivetrain + module constants factory
# ---------------------------------------------------------------------------

DRIVETRAIN_CONSTANTS = SwerveDrivetrainConstants()
DRIVETRAIN_CONSTANTS.can_bus_name = CAN_BUS_NAME
DRIVETRAIN_CONSTANTS.pigeon2_id = PIGEON2_ID


def _make_module(
    steer_id: int,
    drive_id: int,
    encoder_id: int,
    encoder_offset: float,
    x_pos: float,
    y_pos: float,
    invert_drive: bool,
    steer_inverted: bool,
    encoder_inverted: bool,
) -> SwerveModuleConstants:
    """Create a SwerveModuleConstants for one swerve module."""
    mod = SwerveModuleConstants()

    mod.steer_motor_id = steer_id
    mod.drive_motor_id = drive_id
    mod.encoder_id = encoder_id
    mod.encoder_offset = encoder_offset

    mod.location_x = x_pos
    mod.location_y = y_pos

    mod.drive_motor_inverted = invert_drive
    mod.steer_motor_inverted = steer_inverted
    mod.encoder_inverted = encoder_inverted

    mod.steer_motor_gains = STEER_GAINS
    mod.drive_motor_gains = DRIVE_GAINS

    mod.steer_motor_closed_loop_output = STEER_CLOSED_LOOP_OUTPUT
    mod.drive_motor_closed_loop_output = DRIVE_CLOSED_LOOP_OUTPUT

    mod.slip_current = SLIP_CURRENT
    mod.speed_at_12_volts = SPEED_AT_12V

    mod.drive_motor_gear_ratio = DRIVE_GEAR_RATIO
    mod.steer_motor_gear_ratio = STEER_GEAR_RATIO
    mod.coupling_gear_ratio = COUPLE_RATIO
    mod.wheel_radius = WHEEL_RADIUS

    mod.drive_motor_type = DRIVE_MOTOR_TYPE
    mod.steer_motor_type = STEER_MOTOR_TYPE
    mod.feedback_source = STEER_FEEDBACK_TYPE

    mod.drive_motor_initial_configs = DRIVE_INITIAL_CONFIGS
    mod.steer_motor_initial_configs = STEER_INITIAL_CONFIGS
    mod.encoder_initial_configs = ENCODER_INITIAL_CONFIGS

    mod.steer_inertia = STEER_INERTIA
    mod.drive_inertia = DRIVE_INERTIA
    mod.steer_friction_voltage = STEER_FRICTION_VOLTAGE
    mod.drive_friction_voltage = DRIVE_FRICTION_VOLTAGE

    return mod


FRONT_LEFT = _make_module(
    FL_STEER_ID,
    FL_DRIVE_ID,
    FL_ENCODER_ID,
    FL_ENCODER_OFFSET,
    FL_X_POS,
    FL_Y_POS,
    INVERT_LEFT_SIDE,
    FL_STEER_INVERTED,
    FL_ENCODER_INVERTED,
)
FRONT_RIGHT = _make_module(
    FR_STEER_ID,
    FR_DRIVE_ID,
    FR_ENCODER_ID,
    FR_ENCODER_OFFSET,
    FR_X_POS,
    FR_Y_POS,
    INVERT_RIGHT_SIDE,
    FR_STEER_INVERTED,
    FR_ENCODER_INVERTED,
)
BACK_LEFT = _make_module(
    BL_STEER_ID,
    BL_DRIVE_ID,
    BL_ENCODER_ID,
    BL_ENCODER_OFFSET,
    BL_X_POS,
    BL_Y_POS,
    INVERT_LEFT_SIDE,
    BL_STEER_INVERTED,
    BL_ENCODER_INVERTED,
)
BACK_RIGHT = _make_module(
    BR_STEER_ID,
    BR_DRIVE_ID,
    BR_ENCODER_ID,
    BR_ENCODER_OFFSET,
    BR_X_POS,
    BR_Y_POS,
    INVERT_RIGHT_SIDE,
    BR_STEER_INVERTED,
    BR_ENCODER_INVERTED,
)

# Max angular rate for teleop
MAX_ANGULAR_RATE = 0.75 * 2 * math.pi  # 3/4 rotation/s in rad/s

# Default teleop speed divider
DEFAULT_SPEED_DIVIDER = 3.0


def create_drivetrain():
    """Create the CommandSwerveDrivetrain. Call once in RobotContainer."""
    from subsystems.command_swerve_drivetrain import CommandSwerveDrivetrain

    return CommandSwerveDrivetrain(
        DRIVETRAIN_CONSTANTS, FRONT_LEFT, FRONT_RIGHT, BACK_LEFT, BACK_RIGHT
    )
